# Generated by Django 5.2.5 on 2026-03-17

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("iata_code", models.CharField(blank=True, max_length=3)),
                ("icao_code", models.CharField(blank=True, max_length=4)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="invoice_app_name_1b2d14_idx"),
                    models.Index(fields=["iata_code"], name="invoice_app_iata_co_1c4a54_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="invoice_app_name_6d0f4c_idx"),
                    models.Index(fields=["gstin"], name="invoice_app_gstin_0b7d21_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.CharField(max_length=40, unique=True)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("PARTIALLY_PAID", "Partially Paid"), ("PAID", "Paid"), ("OVERDUE", "Overdue"), ("CANCELLED", "Cancelled")], default="ISSUED", max_length=20)),
                ("is_flagged", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("airline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoices", to="invoice_app.airline")),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="invoice_app.vendor")),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["invoice_no"], name="invoice_app_invoic_167a2e_idx"),
                    models.Index(fields=["issue_date"], name="invoice_app_issue__5b7c1e_idx"),
                    models.Index(fields=["due_date"], name="invoice_app_due_da_ee133c_idx"),
                    models.Index(fields=["status"], name="invoice_app_status_90e0c8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="invoice_app.invoice")),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["invoice"], name="invoice_app_invoic_4d5b1b_idx"),
                ],
            },
        ),
    ]
